[package]
name = "typid"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

[features]
default = ["serde", "jsonschema"]
jsonschema = ["dep:schemars"]
serde = ["dep:serde", "dep:serde_json"]

[dependencies]
serde = { optional = true, workspace = true }
serde_json = { optional = true, workspace = true }
sqlx = { workspace = true, features = [ "rust_decimal", "uuid" ] }
typid_derive = { path = "typid_derive" }
utoipa = {workspace = true}
uuid = { workspace = true }
schemars = { optional = true, workspace = true }

[dev-dependencies]
serde_json = {workspace = true}
rstest = {workspace = true}

[lints]
workspace = true
